"""empty message

Revision ID: 2948b9a5f074
Revises: 
Create Date: 2021-03-22 12:37:54.961029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2948b9a5f074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_proprietario',
    sa.Column('id_proprietario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_proprietario', sa.String(), nullable=True),
    sa.Column('cpf_proprietario', sa.String(), nullable=True),
    sa.Column('rg_proprietario', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('profissao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_proprietario'),
    sa.UniqueConstraint('id_proprietario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_proprietario')
    # ### end Alembic commands ###
