"""empty message

Revision ID: b5f95f9f9756
Revises: 2948b9a5f074
Create Date: 2021-03-24 00:20:05.829522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f95f9f9756'
down_revision = '2948b9a5f074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_proprietario', ['id_proprietario'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_proprietario', type_='unique')
    # ### end Alembic commands ###
