"""empty message

Revision ID: d3be20c5a2a1
Revises: b5f95f9f9756
Create Date: 2021-03-24 00:23:04.671640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3be20c5a2a1'
down_revision = 'b5f95f9f9756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cliente',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_cliente', sa.String(), nullable=True),
    sa.Column('cpf_cliente', sa.String(), nullable=True),
    sa.Column('rg_cliente', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('profissao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('id_cliente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_cliente')
    # ### end Alembic commands ###
